[package]
authors = ["Ryan Summers <ryan.summers@vertigo-designs.com>"]
edition = "2018"
readme = "README.md"
name = "booster"
version = "0.2.0"
build = "build.rs"
resolver = "2"

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.10"
cortex-m-rtic = "0.5.3"
embedded-hal = "0.2.4"
enum-iterator = "0.6.0"
cortex-m-log = { version = "0.6.1", features = ["log-integration"] }
log = "0.4.8"
heapless = { version = "0.7", features = ["serde"] }
bit_field = "0.10.0"
debounced-pin = "0.3.0"
serde = {version = "1.0", features = ["derive"], default-features = false }
serde-json-core = "0.2"
logos = { version = "0.11.4", default-features = false, features = ["export_derive"] }
bbqueue = "0.4.10"
usbd-serial = "0.1.0"
shared-bus = { version = "0.2.0-alpha.1", features = ["cortex-m"] }
usb-device = "0.2.6"
postcard = "0.5.1"
crc-any = { version = "2.3.5", default-features = false }
panic-persist = { git = "https://github.com/jamesmunns/panic-persist", branch = "master", features = ["custom-panic-handler"] }
smoltcp-nal = { version = "0.2.0", optional = true }
embedded-time = { version = "0.12.0", optional = true }
minimq = "0.5"

[build-dependencies]
built = { version = "0.5", features = ["git2", "chrono"], default-features = false }

[dependencies.stm32f4xx-hal]
git = "https://github.com/stm32-rs/stm32f4xx-hal"
features = ["stm32f407", "rt", "usb_fs"]

[dependencies.w5500]
git = "https://github.com/quartiq/w5500"
branch = "feature/tcp-nal"
optional = true

[dependencies.enc424j600]
git = "https://git.m-labs.hk/M-Labs/ENC424J600.git"
rev = "fbcc3778d27cfbeec7a1395c9b13a00c8a26af9a"
features = [ "smoltcp-phy", "cortex-m-cpu" ]
optional = true

[dependencies.ad5627]
path = "ad5627"

[dependencies.ads7924]
path = "ads7924"

[dependencies.dac7571]
path = "dac7571"

[dependencies.max6639]
path = "max6639"

[dependencies.max6642]
path = "max6642"

[dependencies.mcp3221]
path = "mcp3221"

[dependencies.microchip-24aa02e48]
path = "microchip-24aa02e48"

[dependencies.tca9548]
path = "tca9548"

[features]
unstable = []
phy_enc424j600 = [ "enc424j600", "smoltcp-nal", "embedded-time" ]
phy_w5500 = [ "w5500" ]
default = [ "phy_w5500" ]

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
