name: Continuous Integration

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          components: clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy

  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
        variant: [phy_w5500, phy_enc424j600]
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf
          override: true
          components: llvm-tools-preview

      - name: Install Binutils
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-binutils

      - name: Style Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose

      - name: Build [Debug]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features "${{ matrix.variant }}"

      - name: Build [Release]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features "${{ matrix.variant }}"

      - name: Generate Release
        uses: actions-rs/cargo@v1
        with:
          command: objcopy
          args: --release --no-default-features --features "${{ matrix.variant }}" --verbose -- -O binary booster-release.bin

      - name: Upload Release
        uses: actions/upload-artifact@v2
        if: ${{ matrix.toolchain == 'stable' }} &&
            (${{ github.ref == 'refs/heads/master' }} ||
             ${{ github.ref == 'refs/heads/develop' }})
        with:
          name: Firmware Images (variant=${{ matrix.variant }})
          path: |
            target/*/release/booster
            booster-release.bin

  compile-unstable:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [phy_w5500, phy_enc424j600]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7em-none-eabihf
          override: true
      - name: cargo build+unstable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features "unstable ${{ matrix.variant }}"
      - name: cargo build+release+unstable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features "unstable ${{ matrix.variant }}"
