name: Continuous Integration

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
    # UTC
    - cron: '48 4 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  compile:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      max-parallel: 2
      matrix:
        toolchain:
          - stable
          - '1.57.0'
        features:
          - phy_w5500
          - phy_enc424j600
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf
          override: true
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v1
        if: ${{ matrix.toolchain != 'nightly' }}

      - name: Install Binutils
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-binutils

      - name: Build [Debug]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features "${{ matrix.features }}"

      - name: Build [Release]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features "${{ matrix.features }}"

      - name: Extract Binary
        uses: actions-rs/cargo@v1
        with:
          command: objcopy
          args: --release --no-default-features --features "${{ matrix.features }}" --verbose -- -O binary booster-release.bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ matrix.toolchain == 'stable'
          && (github.ref == 'refs/heads/master'
          || github.ref == 'refs/heads/develop') }}
        with:
          name: Firmware Images (features=${{ matrix.features }})
          path: |
            target/*/release/booster
            booster-release.bin
